
// SECURITY NOTE: SQL Scripts must be executed directly in the Database Console.

export const SUPABASE_SQL_SCRIPT = `
-- =================================================================
-- E-FINANCE DATABASE SCHEMA (V16 - FULL MIGRATION SCRIPT)
-- Execute este script no SQL Editor do Supabase para garantir
-- que todas as tabelas, funções e políticas estejam atualizadas.
-- =================================================================

-- 1. Habilita Extensões
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Tabela de Tenants (Organizações)
CREATE TABLE IF NOT EXISTS public.tenants (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    logo_url TEXT,
    owner_name TEXT,
    owner_email TEXT,
    pix_key TEXT,
    pix_key_type TEXT DEFAULT 'CNPJ',
    pix_name TEXT,
    pix_city TEXT,
    support_whatsapp TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabela de Perfis
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE,
    full_name TEXT,
    role TEXT DEFAULT 'investor' CHECK (role IN ('admin', 'investor', 'debtor')), 
    cpf TEXT,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_tenant_cpf ON public.profiles (tenant_id, cpf) WHERE cpf IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_tenant_email ON public.profiles (tenant_id, email) WHERE email IS NOT NULL;
ALTER TABLE public.profiles ALTER COLUMN tenant_id SET NOT NULL;


-- 4. Tabela de Convites
CREATE TABLE IF NOT EXISTS public.invites (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    code TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('investor', 'debtor')),
    full_name TEXT,
    email TEXT,
    phone_number TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted')),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() + interval '7 days'),
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    accepted_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Tabelas Financeiras
CREATE TABLE IF NOT EXISTS public.investments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    payer_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    asset_name TEXT NOT NULL,
    amount_invested NUMERIC NOT NULL,
    current_value NUMERIC NOT NULL,
    interest_rate NUMERIC DEFAULT 0,
    installment_value NUMERIC DEFAULT 0,
    total_installments INTEGER DEFAULT 1,
    type TEXT DEFAULT 'Financing',
    frequency TEXT DEFAULT 'monthly',
    due_day INTEGER,
    weekday INTEGER,
    start_date DATE,
    calculation_mode TEXT,
    source_capital NUMERIC DEFAULT 0,
    source_profit NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.loan_installments (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    investment_id BIGINT REFERENCES public.investments(id) ON DELETE CASCADE,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    number INTEGER NOT NULL,
    due_date DATE NOT NULL,
    amount_principal NUMERIC DEFAULT 0,
    amount_interest NUMERIC DEFAULT 0,
    amount_total NUMERIC NOT NULL,
    amount_paid NUMERIC DEFAULT 0,
    fine_amount NUMERIC DEFAULT 0,
    interest_delay_amount NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'pending', 
    paid_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Funções Auxiliares de Segurança
CREATE OR REPLACE FUNCTION public.get_tenant_id_safe()
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth, extensions AS $$
DECLARE tid uuid;
BEGIN
  SELECT (current_setting('request.jwt.claims', true)::jsonb -> 'app_metadata' ->> 'tenant_id')::uuid INTO tid;
  IF tid IS NULL THEN SELECT tenant_id INTO tid FROM public.profiles WHERE id = auth.uid(); END IF;
  RETURN tid;
END;
$$;

-- 7. Trigger de Auth (Criação de Usuário)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
    new_tenant_id UUID;
    invite_record RECORD;
    generated_slug TEXT;
BEGIN
    IF (new.raw_user_meta_data->>'invite_code') IS NOT NULL THEN
        SELECT * INTO invite_record FROM public.invites WHERE code = (new.raw_user_meta_data->>'invite_code') AND status = 'pending' AND expires_at > now();
        IF NOT FOUND THEN RAISE EXCEPTION 'Código de convite inválido, expirado ou já utilizado.'; END IF;

        INSERT INTO public.profiles (id, email, full_name, role, tenant_id)
        VALUES (new.id, new.email, COALESCE(new.raw_user_meta_data->>'full_name', invite_record.full_name), invite_record.role, invite_record.tenant_id);
        
        UPDATE public.invites SET status = 'accepted', accepted_by = new.id, updated_at = now() WHERE id = invite_record.id;
        
        UPDATE auth.users SET raw_app_meta_data = raw_app_meta_data || jsonb_build_object('tenant_id', invite_record.tenant_id) WHERE id = new.id;
    ELSIF (new.raw_user_meta_data->>'company_name') IS NOT NULL THEN
        generated_slug := lower(regexp_replace(new.raw_user_meta_data->>'company_name', E'[^\\w]+', '-', 'g')) || '-' || floor(random()*10000)::text;
        
        INSERT INTO public.tenants (name, slug, owner_name, owner_email)
        VALUES (new.raw_user_meta_data->>'company_name', generated_slug, new.raw_user_meta_data->>'full_name', new.email)
        RETURNING id INTO new_tenant_id;
        
        INSERT INTO public.profiles (id, email, full_name, role, tenant_id)
        VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', 'admin', new_tenant_id);
        
        UPDATE auth.users SET raw_app_meta_data = raw_app_meta_data || jsonb_build_object('tenant_id', new_tenant_id) WHERE id = new.id;
    ELSE
        RAISE EXCEPTION 'Cadastro não permitido. Use um código de convite ou registre uma nova empresa.';
    END IF;
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 8. Funções RPC (Chamadas pelo Frontend)
CREATE OR REPLACE FUNCTION public.generate_invite_code(p_full_name TEXT, p_email TEXT, p_phone_number TEXT, p_role TEXT)
RETURNS TEXT LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE new_code TEXT; admin_id UUID := auth.uid(); tenant_id UUID;
BEGIN
    SELECT profiles.tenant_id INTO tenant_id FROM public.profiles WHERE id = admin_id;
    IF tenant_id IS NULL THEN RAISE EXCEPTION 'Admin profile not found or tenant not linked.'; END IF;
    LOOP
        new_code := upper(substr(md5(random()::text), 0, 9));
        EXIT WHEN NOT EXISTS (SELECT 1 FROM public.invites WHERE code = new_code);
    END LOOP;
    INSERT INTO public.invites (tenant_id, code, role, full_name, email, phone_number, created_by)
    VALUES (tenant_id, new_code, p_role, p_full_name, p_email, p_phone_number, admin_id);
    RETURN new_code;
END;
$$;

-- Adicionar outras funções RPC aqui (ex: create_investment_validated, pay_installment, etc.)

-- 9. Políticas de Segurança (ROW LEVEL SECURITY)
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loan_installments ENABLE ROW LEVEL SECURITY;

-- Limpa políticas antigas para evitar conflitos
DO $$
DECLARE r RECORD;
BEGIN FOR r IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') LOOP
EXECUTE 'DROP POLICY IF EXISTS ' || quote_ident(r.policyname) || ' ON ' || quote_ident(r.tablename);
END LOOP; END;
$$;

-- Políticas de Acesso
CREATE POLICY "Allow public read access on tenants" ON public.tenants FOR SELECT USING (true);
CREATE POLICY "Allow admin to manage their own tenant" ON public.tenants FOR ALL USING (id = get_tenant_id_safe() AND (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Users can view profiles in their own tenant" ON public.profiles FOR SELECT USING (tenant_id = get_tenant_id_safe());
CREATE POLICY "Admin can manage profiles in their tenant" ON public.profiles FOR ALL USING (tenant_id = get_tenant_id_safe() AND (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Admin can manage invites for their tenant" ON public.invites FOR ALL USING (tenant_id = get_tenant_id_safe() AND (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Users can view financial data in their tenant" ON public.investments FOR SELECT USING (tenant_id = get_tenant_id_safe());
CREATE POLICY "Admin can manage investments in their tenant" ON public.investments FOR ALL USING (tenant_id = get_tenant_id_safe() AND (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Users can view installments in their tenant" ON public.loan_installments FOR SELECT USING (tenant_id = get_tenant_id_safe());
CREATE POLICY "Admin can manage installments in their tenant" ON public.loan_installments FOR ALL USING (tenant_id = get_tenant_id_safe() AND (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');


-- 10. Permissões de Acesso
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated, service_role;

-- Finaliza a configuração
-- Grant anon permissions (necessário para login/signup)
GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT ON public.tenants TO anon;

-- Garante que o usuário autenticado pode executar as funções RPC
GRANT EXECUTE ON FUNCTION public.generate_invite_code(text, text, text, text) TO authenticated;
-- (Adicionar GRANT EXECUTE para outras funções RPC aqui)
`;
