import type { CapabilityDefinition, ActionCapability } from './contracts';

const REGISTRY: Record<ActionCapability, CapabilityDefinition> = {
  show_dashboard: {
    name: 'show_dashboard',
    kind: 'query',
    rolesAllowed: ['admin'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'session',
    legacyIntent: 'ver_dashboard',
  },
  list_receivables: {
    name: 'list_receivables',
    kind: 'query',
    rolesAllowed: ['admin'],
    requiredArgs: [],
    optionalArgs: ['filter'],
    requiresConfirmation: false,
    idempotencyScope: 'session',
    legacyIntent: 'listar_recebiveis',
  },
  list_collection_targets: {
    name: 'list_collection_targets',
    kind: 'query',
    rolesAllowed: ['admin'],
    requiredArgs: ['time_window'],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'session',
    legacyIntent: 'cobrar_hoje',
  },
  query_debtor_balance: {
    name: 'query_debtor_balance',
    kind: 'query',
    rolesAllowed: ['admin'],
    requiredArgs: [],
    optionalArgs: ['debtor_name', 'debtor_profile_id'],
    requiresConfirmation: false,
    idempotencyScope: 'session',
    legacyIntent: 'buscar_usuario',
  },
  query_receivables_window: {
    name: 'query_receivables_window',
    kind: 'query',
    rolesAllowed: ['admin'],
    requiredArgs: ['time_window'],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'session',
    legacyIntent: 'recebiveis_periodo',
  },
  query_collection_window: {
    name: 'query_collection_window',
    kind: 'query',
    rolesAllowed: ['admin'],
    requiredArgs: ['time_window'],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'session',
    legacyIntent: 'cobrar_periodo',
  },
  create_contract: {
    name: 'create_contract',
    kind: 'mutation',
    rolesAllowed: ['admin'],
    requiredArgs: [],
    optionalArgs: ['debtor_name', 'debtor_cpf', 'amount', 'rate', 'installments', 'frequency'],
    requiresConfirmation: false,
    idempotencyScope: 'mutation',
    legacyIntent: 'criar_contrato',
  },
  mark_installment_paid: {
    name: 'mark_installment_paid',
    kind: 'mutation',
    rolesAllowed: ['admin'],
    requiredArgs: [],
    optionalArgs: ['contract_id', 'installment_number', 'installment_month', 'installment_year', 'debtor_name'],
    requiresConfirmation: false,
    idempotencyScope: 'mutation',
    legacyIntent: 'marcar_pagamento',
  },
  disconnect_bot: {
    name: 'disconnect_bot',
    kind: 'mutation',
    rolesAllowed: ['admin', 'investor', 'debtor'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: true,
    idempotencyScope: 'mutation',
    legacyIntent: 'desconectar',
  },
  help: {
    name: 'help',
    kind: 'utility',
    rolesAllowed: ['admin', 'investor', 'debtor'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'none',
    legacyIntent: 'ajuda',
  },
  smalltalk_identity: {
    name: 'smalltalk_identity',
    kind: 'utility',
    rolesAllowed: ['admin', 'investor', 'debtor'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'none',
  },
  smalltalk_datetime: {
    name: 'smalltalk_datetime',
    kind: 'utility',
    rolesAllowed: ['admin', 'investor', 'debtor'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'none',
  },
  generate_report: {
    name: 'generate_report',
    kind: 'query',
    rolesAllowed: ['admin'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'session',
    legacyIntent: 'gerar_relatorio',
  },
  generate_invite: {
    name: 'generate_invite',
    kind: 'mutation',
    rolesAllowed: ['admin'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'mutation',
    legacyIntent: 'gerar_convite',
  },
  view_my_installments: {
    name: 'view_my_installments',
    kind: 'query',
    rolesAllowed: ['debtor'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'session',
  },
  view_my_debt_summary: {
    name: 'view_my_debt_summary',
    kind: 'query',
    rolesAllowed: ['debtor'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'session',
  },
  view_my_portfolio: {
    name: 'view_my_portfolio',
    kind: 'query',
    rolesAllowed: ['investor'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'session',
  },
  configure_briefing: {
    name: 'configure_briefing',
    kind: 'mutation',
    rolesAllowed: ['admin'],
    requiredArgs: [],
    optionalArgs: ['briefing_time', 'briefing_enabled'],
    requiresConfirmation: false,
    idempotencyScope: 'mutation',
  },
  preview_lembrete: {
    name: 'preview_lembrete',
    kind: 'query',
    rolesAllowed: ['admin'],
    requiredArgs: [],
    optionalArgs: [],
    requiresConfirmation: false,
    idempotencyScope: 'session',
  },
};

export function getCapabilityDefinition(capability: ActionCapability): CapabilityDefinition {
  return REGISTRY[capability];
}
