import type { FlowMapping } from './types.js';

export const FLOW_MAP: FlowMapping[] = [
  {
    filePattern: 'QuickContractInput.tsx',
    flowName: 'contract-creation-ai',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'LegacyContractPage.tsx',
    flowName: 'legacy-contract',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'high',
    hasInputs: true,
  },
  // PaymentModal casa por substring — pega também o PaymentModal exportado por
  // InstallmentModals.tsx (baixa de pagamento do admin).
  {
    filePattern: 'PaymentModal.tsx',
    flowName: 'payment',
    testFiles: ['e2e/payment/installment-payment.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'InstallmentDetailFlow.tsx',
    flowName: 'payment',
    testFiles: ['e2e/payment/installment-payment.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'InstallmentRowActions.tsx',
    flowName: 'payment',
    testFiles: ['e2e/payment/installment-payment.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
  },
  {
    filePattern: 'CollectionDashboard.tsx',
    flowName: 'collection',
    testFiles: ['e2e/admin/dashboard.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
  },
  {
    filePattern: 'DailyCollectionView.tsx',
    flowName: 'collection',
    testFiles: ['e2e/admin/dashboard.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
  },
  {
    filePattern: 'Dashboard.tsx',
    flowName: 'dashboard-kpis',
    testFiles: ['e2e/admin/dashboard.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'medium',
  },
  {
    filePattern: 'useDashboardData.ts',
    flowName: 'dashboard-kpis',
    testFiles: ['e2e/admin/dashboard.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'medium',
  },
  // Sobreviveu à remoção das telas de investidor: hoje só exporta os helpers puros
  // (computeMonthlyView etc.) que alimentam a aba "Visão Mensal" do admin.
  {
    filePattern: 'useInvestorMetrics.ts',
    flowName: 'monthly-view',
    testFiles: ['e2e/reports/dashboard-monthly.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
  },
  {
    filePattern: 'MonthlyInvestorView.tsx',
    flowName: 'monthly-view',
    testFiles: ['e2e/reports/dashboard-monthly.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
  },
  {
    filePattern: 'AdminUsers.tsx',
    flowName: 'user-mgmt',
    testFiles: ['e2e/admin/users.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'low',
    hasInputs: true,
  },
  {
    filePattern: 'AdminUserDetails.tsx',
    flowName: 'user-mgmt',
    testFiles: ['e2e/admin/users.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'low',
  },
  {
    filePattern: 'AdminContracts.tsx',
    flowName: 'admin-contracts',
    testFiles: ['e2e/admin/dashboard.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'medium',
    hasInputs: true,
  },
  {
    filePattern: 'AdminAssistant.tsx',
    flowName: 'admin-assistant',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'low',
  },
  {
    filePattern: 'ContractDetail.tsx',
    flowName: 'contract-detail',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'medium',
  },
  {
    filePattern: 'SubscriptionTab.tsx',
    flowName: 'subscription',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'low',
  },
  {
    filePattern: 'Login.tsx',
    flowName: 'auth+routing',
    testFiles: ['e2e/auth/login.spec.ts'],
    playwrightProject: 'no-auth',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'App.tsx',
    flowName: 'auth+routing',
    testFiles: ['e2e/auth/login.spec.ts'],
    playwrightProject: 'no-auth',
    risk: 'high',
  },
  {
    filePattern: 'OnboardingWizard.tsx',
    flowName: 'onboarding',
    testFiles: [],
    playwrightProject: 'no-auth',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'SetupWizard.tsx',
    flowName: 'setup',
    testFiles: [],
    playwrightProject: 'no-auth',
    risk: 'medium',
    hasInputs: true,
  },
  {
    filePattern: 'AdminSettings.tsx',
    flowName: 'settings',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'medium',
    hasInputs: true,
  },
  {
    // A renovação deixou de ter tela própria: virou o wizard de AdminContracts
    // pré-preenchido, com o vínculo pai→filho feito dentro do RPC. A cobertura
    // vive em contract-lifecycle.spec.ts (CNT-LC-01/06/07).
    filePattern: 'AdminContracts.tsx',
    flowName: 'contract-renewal',
    testFiles: ['e2e/contract/contract-lifecycle.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'InstallmentModals.tsx',
    flowName: 'payment',
    testFiles: ['e2e/payment/installment-payment.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'ResetPassword.tsx',
    flowName: 'auth+routing',
    testFiles: [],
    playwrightProject: 'no-auth',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'services/supabase.ts',
    flowName: 'ALL',
    testFiles: ['ALL'],
    playwrightProject: 'all',
    risk: 'high',
  },
  {
    filePattern: 'types.ts',
    flowName: 'ALL',
    testFiles: ['ALL'],
    playwrightProject: 'all',
    risk: 'high',
  },
  {
    filePattern: 'constants.ts',
    flowName: 'ALL',
    testFiles: ['ALL'],
    playwrightProject: 'all',
    risk: 'high',
  },
  {
    filePattern: 'index.css',
    flowName: 'visual',
    testFiles: ['ALL'],
    playwrightProject: 'all',
    risk: 'low',
  },
];

/** All known E2E spec files */
export const ALL_SPEC_FILES = [
  'e2e/auth/login.spec.ts',
  'e2e/admin/dashboard.spec.ts',
  'e2e/admin/users.spec.ts',
  'e2e/payment/installment-payment.spec.ts',
  'e2e/reports/dashboard-monthly.spec.ts',
  'e2e/edge-cases.spec.ts',
];

/** Patterns for files that don't affect testable flows */
export const IGNORED_PATTERNS = [
  /^docs\//,
  /^\.claude\//,
  /^\.aios/,
  /^e-finance-bot\//,
  /\.md$/,
  /^supabase\//,
  /^context\//,
];
