import type { FlowMapping } from './types.js';

export const FLOW_MAP: FlowMapping[] = [
  {
    filePattern: 'QuickContractInput.tsx',
    flowName: 'contract-creation-ai',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'LegacyContractPage.tsx',
    flowName: 'legacy-contract',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'PaymentModal.tsx',
    flowName: 'payment',
    testFiles: ['e2e/debtor/dashboard.spec.ts'],
    playwrightProject: 'chromium-debtor',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'InstallmentDetailFlow.tsx',
    flowName: 'payment',
    testFiles: ['e2e/debtor/dashboard.spec.ts'],
    playwrightProject: 'chromium-debtor',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'InstallmentRowActions.tsx',
    flowName: 'payment',
    testFiles: ['e2e/debtor/dashboard.spec.ts'],
    playwrightProject: 'chromium-debtor',
    risk: 'high',
  },
  {
    filePattern: 'CollectionDashboard.tsx',
    flowName: 'collection',
    testFiles: ['e2e/admin/dashboard.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
  },
  {
    filePattern: 'DailyCollectionView.tsx',
    flowName: 'collection',
    testFiles: ['e2e/admin/dashboard.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'high',
  },
  {
    filePattern: 'Dashboard.tsx',
    flowName: 'dashboard-kpis',
    testFiles: ['e2e/admin/dashboard.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'medium',
  },
  {
    filePattern: 'useDashboardData.ts',
    flowName: 'dashboard-kpis',
    testFiles: ['e2e/admin/dashboard.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'medium',
  },
  {
    filePattern: 'InvestorDashboard.tsx',
    flowName: 'investor-dash',
    testFiles: ['e2e/investor/dashboard.spec.ts'],
    playwrightProject: 'chromium-investor',
    risk: 'medium',
  },
  {
    filePattern: 'useInvestorMetrics.ts',
    flowName: 'investor-dash',
    testFiles: ['e2e/investor/dashboard.spec.ts'],
    playwrightProject: 'chromium-investor',
    risk: 'medium',
  },
  {
    filePattern: 'DebtorDashboard.tsx',
    flowName: 'debtor-dash',
    testFiles: ['e2e/debtor/dashboard.spec.ts'],
    playwrightProject: 'chromium-debtor',
    risk: 'medium',
  },
  {
    filePattern: 'useDebtorFinance.ts',
    flowName: 'debtor-dash',
    testFiles: ['e2e/debtor/dashboard.spec.ts'],
    playwrightProject: 'chromium-debtor',
    risk: 'medium',
  },
  {
    filePattern: 'AdminUsers.tsx',
    flowName: 'user-mgmt',
    testFiles: ['e2e/admin/users.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'low',
    hasInputs: true,
  },
  {
    filePattern: 'AdminUserDetails.tsx',
    flowName: 'user-mgmt',
    testFiles: ['e2e/admin/users.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'low',
  },
  {
    filePattern: 'AdminContracts.tsx',
    flowName: 'admin-contracts',
    testFiles: ['e2e/admin/dashboard.spec.ts'],
    playwrightProject: 'chromium',
    risk: 'medium',
    hasInputs: true,
  },
  {
    filePattern: 'AdminAssistant.tsx',
    flowName: 'admin-assistant',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'low',
  },
  {
    filePattern: 'ContractDetail.tsx',
    flowName: 'contract-detail',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'medium',
  },
  {
    filePattern: 'SubscriptionTab.tsx',
    flowName: 'subscription',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'low',
  },
  {
    filePattern: 'Login.tsx',
    flowName: 'auth+routing',
    testFiles: ['e2e/auth/login.spec.ts'],
    playwrightProject: 'no-auth',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'App.tsx',
    flowName: 'auth+routing',
    testFiles: ['e2e/auth/login.spec.ts'],
    playwrightProject: 'no-auth',
    risk: 'high',
  },
  {
    filePattern: 'OnboardingWizard.tsx',
    flowName: 'onboarding',
    testFiles: [],
    playwrightProject: 'no-auth',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'SetupWizard.tsx',
    flowName: 'setup',
    testFiles: [],
    playwrightProject: 'no-auth',
    risk: 'medium',
    hasInputs: true,
  },
  {
    filePattern: 'AdminSettings.tsx',
    flowName: 'settings',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'medium',
    hasInputs: true,
  },
  {
    filePattern: 'ContractRenewalModal.tsx',
    flowName: 'contract-renewal',
    testFiles: [],
    playwrightProject: 'chromium',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'InstallmentModals.tsx',
    flowName: 'payment',
    testFiles: ['e2e/debtor/dashboard.spec.ts'],
    playwrightProject: 'chromium-debtor',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'ResetPassword.tsx',
    flowName: 'auth+routing',
    testFiles: [],
    playwrightProject: 'no-auth',
    risk: 'high',
    hasInputs: true,
  },
  {
    filePattern: 'services/supabase.ts',
    flowName: 'ALL',
    testFiles: ['ALL'],
    playwrightProject: 'all',
    risk: 'high',
  },
  {
    filePattern: 'types.ts',
    flowName: 'ALL',
    testFiles: ['ALL'],
    playwrightProject: 'all',
    risk: 'high',
  },
  {
    filePattern: 'constants.ts',
    flowName: 'ALL',
    testFiles: ['ALL'],
    playwrightProject: 'all',
    risk: 'high',
  },
  {
    filePattern: 'index.css',
    flowName: 'visual',
    testFiles: ['ALL'],
    playwrightProject: 'all',
    risk: 'low',
  },
];

/** All known E2E spec files */
export const ALL_SPEC_FILES = [
  'e2e/auth/login.spec.ts',
  'e2e/admin/dashboard.spec.ts',
  'e2e/admin/users.spec.ts',
  'e2e/investor/dashboard.spec.ts',
  'e2e/debtor/dashboard.spec.ts',
  'e2e/edge-cases.spec.ts',
];

/** Patterns for files that don't affect testable flows */
export const IGNORED_PATTERNS = [
  /^docs\//,
  /^\.claude\//,
  /^\.aios/,
  /^e-finance-bot\//,
  /\.md$/,
  /^supabase\//,
  /^context\//,
];
